#!/bin/bash

# $1 é um nome de variavel , não o seu valor
dereference ()
{
 	y=\$"$1"         				
	echo "Nome do param: $y"

   			  	
	x=`eval "expr \"$y\" "`
	echo $1=$x
	eval "$1=\"Some Different Text \""        # Assign new value.
}

param="Um texto qualquer"
echo $param "antes" 			# valor variavel 

echo “-----------------------------”

dereference param         
echo $param "depois" 			# Some Different Text after

exit 0
